language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install -e .
script:
  - chmod +x ./tests/test_scriptBandsplot.py
  - python ./tests/test_scriptBandsplot.py
  - rm ./tests/test.pdf
after_success:
  - coveralls